name: Wikibase Secondary CI
on:
  [ push ]

jobs:
  secondary-ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
        - env:
            MW_BRANCH: master
            DBTYPE: sqlite
            LANG: ru
            WB: both
          php-versions: '7.3.27'
        - env:
            MW_BRANCH: master
            DBTYPE: sqlite
            LANG: en
            WB: client
          php-versions: '7.2.34'
        - env:
            MW_BRANCH: master
            DBTYPE: mysql
            LANG: en
            WB: repo
          php-versions: '7.2.34'
        - env:
            MW_BRANCH: master
            DBTYPE: sqlite
            LANG: ar
            WB: both
          php-versions: '7.3.27'
        - env:
            MW_BRANCH: master
            DBTYPE: mysql
            LANG: en
            WB: both
          php-versions: '7.2.34'
        - env:
            MW_BRANCH: master
            DBTYPE: mysql
            LANG: en
            WB: both
          php-versions: '7.3.27'
        - env:
            MW_BRANCH: master
            DBTYPE: mysql
            LANG: en
            WB: both
          php-versions: '7.4.15'
       # Be compatible with the previous MediaWiki release branch
        - env:
            MW_BRANCH: REL1_36
            DBTYPE: mysql
            LANG: ru
            WB: both
          php-versions: '7.3.27'
    continue-on-error: ${{ matrix.env.MW_BRANCH == 'REL1_36' }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up MySQL
      uses: mirromutth/mysql-action@v1.1
      with:
        mysql version: '5.7'
        mysql database: 'test_db_wiki'
        mysql root password: 'root'
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: pdo_sqlite, mysqlnd
    - name: Cache Composer cache
      uses: actions/cache@v2
      with:
        path: $HOME/.composer/cache
        key: composer-cache-php${{ matrix.php-versions }}
    - name: install.sh
      env: ${{ matrix.env }}
      run: |
        bash ./build/ci-scripts/install.sh
    - name: Apply WB settings
      env: ${{ matrix.env }}
      run: |
        bash ./build/ci-scripts/mw-apply-wb-settings.sh
    - name: Update DB
      env: ${{ matrix.env }}
      run: |
        bash ./build/ci-scripts/update-db.sh
    - name: Run script
      env: ${{ matrix.env }}
      run: |
        bash ./build/ci-scripts/script.sh
    - name: Send mail
      if: ${{ failure() && matrix.env.MW_BRANCH != 'REL1_36' }}
      run: echo format("Mail would have been sent due to failure on $MATRIX_ENV_MW_BRANCH")
